---
title: "Networks"
author: "Jingxiao Zhang"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Networks HW

### Torkamani A, Schork NJ. Prediction of cancer driver mutations in protein kinases.
Cancer research. 2008;68(6):1675–82. pmid:18339846

```{r}
# Load libraries for network analysis
library(igraph)
library(NetIndices)
```

```{r}
# First a binary protein interaction network constructed from an unbiased yeast2hybrid experimental screen
Y2H <- read.table(file="/Users/jiz225/Desktop/CMM262/Networks_HW/Networks/HI-II-14.tsv",header=T,sep="\t")
print(head(Y2H))
# Second an literature curated network of high confidence protein interactions
lit <- read.table(file="/Users/jiz225/Desktop/CMM262/Networks_HW/Networks/Lit-BM-13.tsv",header=T,sep="\t")
print(head(lit))
#  http://interactome.dfci.harvard.edu/H_sapiens/index.php
```
```{r}
# Load networks
edgelist <- cbind(as.character(Y2H$Symbol.A),as.character(Y2H$Symbol.B))
g <- graph.data.frame(edgelist, directed=F)
edgelist2 <- cbind(as.character(lit$symbol_a),as.character(lit$symbol_b))
g2 <- graph.data.frame(edgelist2, directed=F)
```

```{r}

sprintf('networks generated by yeast2hybrid has %s nodes',length(V(g)))
sprintf('networks generated by literature curation has %s nodes',length(V(g2)))
sprintf('networks generated by yeast2hybrid has %s edges',length(E(g)))
sprintf('networks generated by literature curation has %s edges',length(E(g2)))
gn <- names(V(g))
g2n <- names(V(g2))
```

```{r}
deg.distr.g<-degree.distribution(g,cumulative=T,mode="all")
plot(deg.distr.g,log="xy", ylim=c(.01,10), bg="black",pch=21, xlab="Degree of yeast2hybrid", ylab="Cumulative Frequency")
deg.distr.g2<-degree.distribution(g2,cumulative=T,mode="all")
plot(deg.distr.g2,log="xy", ylim=c(.01,10), bg="black",pch=21, xlab="Degree of literature curation", ylab="Cumulative Frequency")
deg.g <-degree(g,v=V(g))
deg.g2 <-degree(g2,v=V(g2))
power.g<-power.law.fit(deg.g)
power.g2<-power.law.fit(deg.g2)
sprintf('yeast2hybrid nodes follow a power law distribution is %s',power.g$KS.p > 0.05)
sprintf('literature curation nodes follow a power law distribution is %s',power.g2$KS.p > 0.05)
```


```{r}

print(diameter(g))
print(diameter(g2))
```

```{r}
# Load in disease gene lists
mend <- scan("/Users/jiz225/Desktop/CMM262/Networks_HW/OMIM/Mendelian_HGNC.txt",what=as.character())
cancer <- scan("/Users/jiz225/Desktop/CMM262/Networks_HW/Cancer/cancer_genes.2_sources.txt",what=as.character())
length(mend)
length(cancer)
```


```{r}

gn <- names(V(g))
ginmend <- gn[which(gn %in% mend)]
sprintf('The coverage of gene set mend in yeast2hybrid is %1.2f%%',length(ginmend)/length(mend)*100 )
gincancer <- gn[which(gn %in% cancer)]
sprintf('The coverage of gene set cancer in yeast2hybrid is %1.2f%%',length(gincancer)/length(cancer)*100)
sprintf('The Frequency of gene set mend in yeast2hybrid is %1.2f%%',length(ginmend)/length(gn)*100 )
sprintf('The Frequency of gene set cancer in yeast2hybrid is %1.2f%%',length(gincancer)/length(gn)*100)

ginmend <- gn[which(gn %in% mend)]
sprintf('Number of mendelian disease genes in yeast2hybrid is %s',length(ginmend))


gincancer <- gn[which(gn %in% cancer)]
sprintf('Number of cancer genes in g is %s',length(gincancer))

g_nonmend_noncancer <- gn[-which((gn %in% cancer) | (gn %in% mend))]
sprintf('nodes in the graph that are neither cancer nor mendelian disease genes in yeast2hybrid is %s',length(g_nonmend_noncancer))
```


```{r}
g2n <- names(V(g2))

g2inmend <- g2n[which(g2n %in% mend)]
sprintf('Number of mendelian disease genes in literature curation is %s ',length(g2inmend))

g2incancer <- g2n[which(g2n %in% cancer)]
sprintf('Number of cancer genes in literature curation is %s',length(g2incancer))
sprintf('The Frequency of gene set mend in literature derived graph is %1.2f%%',length(g2inmend)/length(g2n)*100 )
sprintf('The Frequency of gene set cancer in literature derived graph is %1.2f%%',length(g2incancer)/length(g2n)*100)

g2_nonmend_noncancer <- g2n[-which((g2n %in% cancer) | (g2n %in% mend))]
sprintf('nodes in the graph that are neither cancer nor mendelian disease genes in literature curation is %s',length(g2_nonmend_noncancer))
```

```{r}
gn <- names(V(g))
g_mend <- gn[which(gn %in% mend)]
g_cancer <- gn[which(gn %in% cancer)]
g_nonmend <- gn[-which(gn %in% mend)]

deg.distr.g_mend <-degree.distribution(g,v=g_mend,cumulative=T)
deg.distr.g_cancer <-degree.distribution(g,v=g_cancer,cumulative=T)
deg.distr.g_non <-degree.distribution(g,v=g_nonmend,cumulative=T)

boxplot(deg.distr.g_mend, deg.distr.g_cancer, deg.distr.g_non, 
        main = "degree distributions for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

clus.coef.g_mend <- transitivity(g, type = "local", vids = g_mend)
clus.coef.g_cancer <- transitivity(g, type = "local", vids = g_cancer)
clus.coef.g_nonmend <- transitivity(g, type = "local", vids = g_nonmend)

boxplot(clus.coef.g_mend, clus.coef.g_cancer, clus.coef.g_nonmend, 
        main = "clustering coeffcient distributions for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

close.g_mend <- closeness(g,vids= g_mend,normalized=T)
close.g_cancer <- closeness(g,vids= g_cancer,normalized=T)
close.g_nonmend <- closeness(g,vids= g_nonmend, normalized=T)

boxplot(close.g_mend, close.g_cancer, close.g_nonmend, 
        main = "closeness centrality for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

bet.g_mend <- betweenness(g,v= g_mend,normalized=T)
bet.g_cancer <- betweenness(g,v= g_cancer,normalized=T)
bet.g_nonmend <- betweenness(g,v= g_nonmend, normalized=T)

boxplot(bet.g_mend, bet.g_cancer, bet.g_nonmend, 
        main = "betweenness centrality for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)
```


```{r}
g2_mend <- g2n[which(g2n %in% mend)]
g2_cancer <- g2n[which(g2n %in% cancer)]
g2_nonmend <- g2n[-which(g2n %in% mend)]

deg.distr.g2_mend <-degree.distribution(g2,v=g2_mend,cumulative=T)
deg.distr.g2_cancer <-degree.distribution(g2,v=g2_cancer,cumulative=T)
deg.distr.g2_non <-degree.distribution(g2,v=g2_nonmend,cumulative=T)

boxplot(deg.distr.g2_mend, deg.distr.g2_cancer, deg.distr.g2_non, 
        main = "degree distributions for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

clus.coef.g2_mend <- transitivity(g2, type = "local", vids = g2_mend)
clus.coef.g2_cancer <- transitivity(g2, type = "local", vids = g2_cancer)
clus.coef.g2_nonmend <- transitivity(g2, type = "local", vids = g2_nonmend)

boxplot(clus.coef.g2_mend, clus.coef.g2_cancer, clus.coef.g2_nonmend, 
        main = "clustering coeffcient distributions for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

close.g2_mend <- closeness(g2,vids= g2_mend,normalized=T)
close.g2_cancer <- closeness(g2,vids= g2_cancer,normalized=T)
close.g2_nonmend <- closeness(g2,vids= g2_nonmend, normalized=T)

boxplot(close.g2_mend, close.g2_cancer, close.g2_nonmend, 
        main = "closeness centrality for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

bet.g2_mend <- betweenness(g2,v= g2_mend,normalized=T)
bet.g2_cancer <- betweenness(g2,v= g2_cancer,normalized=T)
bet.g2_nonmend <- betweenness(g2,v= g2_nonmend, normalized=T)

boxplot(bet.g2_mend, bet.g2_cancer, bet.g2_nonmend, 
        main = "betweenness centrality for genes",
        names = c("disease genes", "cancer genes", "non-disease genes"),
        col = c("orange","red","blue"),
        horizontal = FALSE)

```

```{r}
# Visualize the possible motifs
par(mfrow=c(2,2))
for(i in 1:11){
  test <- graph.isocreate(size=4,i-1,directed=F)
  plot(test)
}

sprintf("Total number of motifs in Y2H network is %s ", count_motifs(g,size=4))
sprintf("Total number of motifs in literature network is %s ", count_motifs(g2,size=4))
g_mot <- motifs(g,size=4)
g2_mot <- motifs(g2,size=4)
sum_mot_g <- 0
for (i in 1:11) {
  if (!is.na(g_mot[i])) {
    sum_mot_g = sum_mot_g + g_mot[i]
  }
}
sum_mot_g2 <- 0
for (i in 1:11) {
  if (!is.na(g2_mot[i])) {
    sum_mot_g2 = sum_mot_g2 + g2_mot[i]
  }
}
print('Frequency of each motif is ')
print(g_mot/sum_mot_g)
print(g2_mot/sum_mot_g2)

```
